# Use an official Python image
FROM python:3.13-slim

# Set the working directory inside the container
WORKDIR /app


# Copy the rest of the application files
COPY . .

# Run the application
CMD ["python", "app.py"]